version: "3.7"

services:
  database:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=drive-cache
    volumes:
      - database-vol:/var/lib/postgresql/data/:rw
  webserver:
    build: .
    ports:
      - 3000:3000
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
volumes:
  # webserver-vol:
  database-vol: