name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

    

jobs:

  build:

    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
    
    - uses: actions/checkout@v3
    - run: ./build.sh
    - run: ./test.sh
   
