name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
    
    - uses: actions/checkout@v3
    - uses: isbang/compose-action@v1.2.0
      with:
        compose-file: "./docker-compose.yml"
    - run: test.sh
   
